name: speech_iot_app
description: "A speech recognition app for a simple iot automation"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^7.3.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  web_socket_channel: ^3.0.3
  rxdart: ^0.28.0
  auto_route: ^10.1.2
  http: ^1.5.0
  bloc_concurrency: ^0.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^10.2.4
  build_runner: ^2.7.1

flutter:
  uses-material-design: true
